### ISSUE TITLE
Idea: add `excluded_tag_pattern` and `included_tag_pattern`

### ISSUE THREAD

**Issue by alexanderjeurissen** [enkessler/cuke_slicer#17]
`cuke_slicer` is great we use it for slicing up our test suite in separate feature files per scenario to reduce variance and better utilize different knapsack workers.

There are two filter options  that is missing is the ability to either include or exclude `tag patterns` in addition to specific tags. I reckon that the patterns would be defined as stringified ruby regexes that are then parsed by `cuke_slicer`.

```ruby
require 'cuke_slicer'

# Choose which part of your test suite that you want to slice up
test_directory = 'path/to/your_test_directory'

# Choose your slicing filters
filters = {
           included_tag_pattern: '<ruby_regex>',
           excluded_paths: 'foo',
           included_paths: [/test_directory/]}

# Use the slicer to find all tests matching those filters
found_tests = CukeSlicer::Slicer.new.slice(test_directory, filters, :file_line)
```

Another option would be to open up the `filters` and allow a block to be passed in addition to a hash, that way one has full control over the filtering.

I'm aware that this can be achieved by passing an empty filter, and using the `:test_object` return type, but I think it would be great if this use-case is somehow supported by cuke_slicer.

**Comment by enkessler** [comment]
So, this one seeks power, eh? Yes, this thing that you ask can be done.

In all seriousness, though, sure, an arbitrary block filter would be handy. I need to put out a new major version of the gem anyway, so I'll give the API an overhaul while I'm at it.

**Comment by enkessler** [comment]
> Another option would be to open up the `filters` and allow a block to be passed in addition to a hash, that way one has full control over the filtering.

@alexanderjeurissen So, it turns out that this is already allowable. I ran across it as I was updating the project.

See https://github.com/enkessler/cuke_slicer/blob/master/testing/cucumber/features/test_case_filtering.feature#L96

**Comment by alexanderjeurissen** [comment]
> > Another option would be to open up the `filters` and allow a block to be passed in addition to a hash, that way one has full control over the filtering.
> 
> @alexanderjeurissen So, it turns out that this is already allowable. I ran across it as I was updating the project.
> 
> See https://github.com/enkessler/cuke_slicer/blob/master/testing/cucumber/features/test_case_filtering.feature#L96

Ah good to know, I completely missed that. Might be worthwhile to include a section in the readme to explain how one can setup a custom filter.

For now we can close this out. Thanks for circling back to me.

**Comment by enkessler** [comment]
Yeah, not all of my projects are as good about pointing users at the feature files for examples. That's on my list of things to do.
