### ISSUE TITLE
File.exists? removed from Ruby 3.2

### ISSUE THREAD

**Issue by gabrielcaamano-ujet** [enkessler/cuke_slicer#19]
## Issue
Starting from Ruby 3.2, the deprecated `File.exists?` method was removed.

Latest gem version published on January 08, 2021 is not updated with this change. This gem version uses the deprecated method in the following lines:
`cuke_slicer-2.2.0/lib/cuke_slicer/slicer.rb:65`

## How to fix
This has already been fixed in master as of February 27, 2021. The commit https://github.com/enkessler/cuke_slicer/commit/5138b55770a757d736677702cf4ce40556d2f75e has not been published.

Please publish a new version to allow for Ruby 3.2 compatibility.

**Comment by enkessler** [comment]
Thanks for the report! I'll try to get a release out this weekend. It will be a major release, now that `Rule` functionality has been added to the slicer and that requires some dependency upgrades too.

**Comment by gabrielcaamano-ujet** [comment]
Thank you!

**Comment by enkessler** [comment]
@gabrielcaamano-ujet A new release has been pushed out. Enjoy.
